### ISSUE TITLE
when run train it gives an error 

### ISSUE THREAD

**Issue by eren-korkmaz** [curiousily/Deep-Learning-For-Hackers#4]
!keras_retinanet/bin/train.py --freeze-backbone --random-transform --weights {PRETRAINED_MODEL} --batch-size 8 --steps 500 --epochs 10 csv annotations.csv classes.csv

Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 540, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 500, in main
    config=args.config
  File "keras_retinanet/bin/train.py", line 114, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 38, in retinanet
    return resnet_retinanet(*args, backbone=self.backbone, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 99, in resnet_retinanet
    resnet = keras_resnet.models.ResNet50(inputs, include_top=False, freeze_bn=True)
  File "/usr/local/lib/python3.6/dist-packages/keras_resnet/models/_2d.py", line 188, in ResNet50
    return ResNet(inputs, blocks, numerical_names=numerical_names, block=keras_resnet.blocks.bottleneck_2d, include_top=include_top, classes=classes, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras_resnet/models/_2d.py", line 66, in ResNet
    x = keras_resnet.layers.BatchNormalization(axis=axis, epsilon=1e-5, freeze=freeze_bn, name="bn_conv1")(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    /usr/local/lib/python3.6/dist-packages/keras_resnet/layers/_batch_normalization.py:17 call  *
        return super(BatchNormalization, self).call(training=(not self.freeze), *args, **kwargs)

    TypeError: type object got multiple values for keyword argument 'training'

**Comment by djkim9031** [comment]
Yeah, I am having the same issue. Please help us!

**Comment by eren-korkmaz** [comment]
find solution:

**dont run this line "!pip install --upgrade keras"**

updated keras not support old keras retinanet
